### PR TITLE
Added In-Memory DB with indexing and Snake/Ladder solutions

### PR DESCRIPTION
**Pull request by TUSHARZ**
- Added In-Memory DB with indexing solution (Complete approach and implementation)
- Added additional Snake and Ladder Solution

I think these would be very helpful.

### CODE REVIEW

**Comment by TUSHARZ** [comment]
@gopalbala

**Comment by TUSHARZ** [comment]
@gopalbala Review

**Review by theritikchoure — APPROVED** [review]
Looks good

**Comment by TUSHARZ** [comment]
@prasadgujar BUMP

**Pull request merged**
